services:
  - type: web
    name: lettersys-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /api/letters
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
